theme: jekyll-theme-cayman

title: [The title of your site]
description: [A short description of your site's purpose]


google_analytics: [Your Google Analytics tracking ID]
# show_downloads: false ["true" or "false" to indicate whether to provide a download URL]
